apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: e12ffm0bm-go 
  janus-idp.io/tekton: e12ffm0bm-go
  backstage.io/kubernetes-id: e12ffm0bm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e12ffm0bm-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml